# Generated by Django 3.2.4 on 2021-06-11 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True)),
                ('rates_number', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=1, default=None, max_digits=2)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model', to='cars.carmake')),
            ],
        ),
        migrations.CreateModel(
            name='CarRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_rate', to='cars.carmodel')),
            ],
        ),
    ]
